version: '3.9'

services:
  app-elzero:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: app-elzero
    restart: always
    working_dir: /app/
    volumes:
      - ./app:/app

  web:
    image: nginx:1.23.3-alpine
    container_name: web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  db:
    container_name: dbase
    image: mysql:8.0.31
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"